# Generated by Django 6.1 on 2026-08-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('capa', models.ImageField(upload_to='series/')),
                ('genero', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('avaliacao', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
